version: '3'
services:
  agent:
    image: optimizely/agent:alpine
    ports:
      - "8080:8080"
      #link agent directory to working agent directory to provide agent/config.yaml <- this has SDK key
    volumes:
      - ./agent/config.yaml:/config.yaml
  minetest:
    image: "registry.gitlab.com/minetest/minetest/server:master"
    #link minetest to server config and custom game lua which uses SDK key to call Agent API -> agent:8080
    #make a sh script to copy the game data and config into the host before spinning up the docker compose? or do it manually?
    volumes:
      - ./minetest/data/:/var/lib/minetest/.minetest/
      # - ./minetest/data/minetest.conf:/var/lib/minetest/.minetest/minetest.conf
   
    #how does shared network work with exposed port for Minetest server?
    ports: 
      - "30000:30000/udp"